# Generated by Django 4.1.4 on 2023-03-08 16:02

# Initialization File For Migrations
from django.db import migrations, models

# Class for MIgration 
class Migration(migrations.Migration):

    initial = True # Initialization

    dependencies = [
    ]

    # List Of Oprations
    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('pn', 'Pens'), ('DR', 'Dairy'), ('NB', 'NOTEBOOK'), ('sc', 'scale'), ('fl', 'files')], max_length=2)),
                ('product_img', models.ImageField(upload_to='product')),
            ],
        ),
    ]

# Ekach laxat thev ki this migrations are done for the initialization of application created