# Generated by Django 4.1.4 on 2023-04-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_product_cart_products_alter_customer_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sc', 'scale'), ('fl', 'files'), ('DR', 'Dairy'), ('pn', 'Pens'), ('NB', 'NOTEBOOK')], max_length=2),
        ),
    ]
