# Generated by Django 4.1.7 on 2023-04-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_category_wishlist_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('On the Way', 'On the Way')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DR', 'Dairy'), ('pn', 'Pens'), ('NB', 'NOTEBOOK'), ('fl', 'files'), ('sc', 'scale')], max_length=2),
        ),
    ]
