"""
Django settings for Project.
Generated by 'django-admin startproject' using Django 4.1.4.

"""
# autoimported path
from pathlib import Path
# Build paths inside the project 
BASE_DIR = Path(__file__).resolve().parent.parent
import smtplib


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ql_p@(g^2c5#hd+evzor#15avm9n-k1@9_%y2$3k6tq%dxibs&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # debugging at (during) development (itself)

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'fakewala12@gmail.com'
EMAIL_HOST_PASSWORD = 'vkqmylmkwclpwmql'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMIAL_BACKEND = 'django.core.mal.backends.smtp.EmailBackend'

ALLOWED_HOSTS = [] # host access controls


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # installed by Saurabh
    'app',
]


# Some packlibs imported by Django itself 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#main root-> rendering path for project
ROOT_URLCONF = 'es.urls'


#Templates to render which will be rquired for implementation(Setting Directory)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Dajgo generated for server connection
WSGI_APPLICATION = 'es.wsgi.application'


# Database
# Django provides sqlite3 database bydefault
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# International-lization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
# For Media Fetching
MEDIA_URL='/media/'  
# Imported by Saurabh



# Default primary key field type
MEDIA_ROOT=BASE_DIR/'media'
# primary field to media directory when registration hits


# to change the path directly to profile
LOGIN_REDIRECT_URL='/profile/'
LOGIN_REDIRECT_URL='/address/'

# Payment Integration Razorpay Keys :
RAZOR_KEY_ID="rzp_test_v2C97myBaohJKR"
RAZOR_KEY_SECRET="JUQP7hv1WldAXkoIXLPLAtyO"

# autogenerated by Django
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'